package main

import "text/template"

const (
	funcArgTmpl  = "%s %s,"
	mapArgTmpl   = "\"%s\": %s,"
	sliceArgTmpl = "%s,"
)

const generatedActionsFileTmplSource = `// Code generated by sql2gogen. DO NOT EDIT.
package {{ .GenPackage }}
{{ if ne (len .ImportPackages) 0 }}
import (
{{- range .ImportPackages }}
	{{ . }}
{{- end }}
)
{{ end }}
{{- range $name, $data := .StmtItems }}	
const {{ $name }} = "{{ $data.Stmt }}"
{{- end}}
{{ range $name, $data := .StmtItems }}
func {{ $data.Function.Name }}(
	{{ $data.Function.Args }}
) (string, {{ $.ReturnValueType }}) {
	return {{ $name }}, {{ $.ReturnValueType }}{
		{{ $data.Function.ReturnValueItems }}
	}
}
{{ end }}
`

var generatedActionsFileTmpl = template.Must(template.New("generated_file").Parse(generatedActionsFileTmplSource))
