// Code generated by sql2gogen. DO NOT EDIT.
package actionsgen

import (
	"time"
)
	
const getProjects = "select * from projects where id = $1;"	
const insertProjects = "insert into projects( id, title, description, createdAt ) values ( $1, $2, $3, $4 );"

func GetProjects(
	projectID string,
) (string, []any) {
	return getProjects, []any{
		projectID,
	}
}

func InsertProjects(
	projectID string, projectTitle string, projectDescription string, createdAt time.Duration,
) (string, []any) {
	return insertProjects, []any{
		projectID, projectTitle, projectDescription, createdAt,
	}
}

