// Code generated by sql2gogen. DO NOT EDIT.
package actionsgen

import (
	"time"
)
	
const getProjects = "select * from projects where id = @projectID;"	
const insertProjects = "insert into projects( id, title, description, createdAt ) values ( @projectID, @projectTitle, @projectDescription, @createdAt );"

func GetProjects(
	projectID string,
) (string, map[string]any) {
	return getProjects, map[string]any{
		"projectID": projectID,
	}
}

func InsertProjects(
	projectID string, projectTitle string, projectDescription string, createdAt time.Duration,
) (string, map[string]any) {
	return insertProjects, map[string]any{
		"projectID": projectID, "projectTitle": projectTitle, "projectDescription": projectDescription, "createdAt": createdAt,
	}
}

