// Code generated by sql2gogen. DO NOT EDIT.
package actionsgen

import (
	"time"
)

var projectStmtMap = map[string]string{	
	"GetProjects": "select * from projects where id = $1;",	
	"InsertProjects": "insert into projects( id, title, description, createdAt ) values ( $1, $2, $3, $4 );",
}


func GetProjects(
	projectID string,
) (string, []any) {
	return projectStmtMap["GetProjects"], []any{
		projectID,
	}
}

func InsertProjects(
	projectID string, projectTitle string, projectDescription string, createdAt time.Duration,
) (string, []any) {
	return projectStmtMap["InsertProjects"], []any{
		projectID, projectTitle, projectDescription, createdAt,
	}
}

