// Code generated by sql2gogen. DO NOT EDIT.
package actionsgen

var userStmtMap = map[string]string{	
	"GetUsers": "select * from users where id = $1 and age > $2;",	
	"InsertUser": "insert into users( id, name, age, email ) values ( $1, $2, $3, $4 );",
}


func GetUsers(
	userID string, userAge int,
) (string, []any) {
	return userStmtMap["GetUsers"], []any{
		userID, userAge,
	}
}

func InsertUser(
	userID string, userName string, userAge int, userEmail string,
) (string, []any) {
	return userStmtMap["InsertUser"], []any{
		userID, userName, userAge, userEmail,
	}
}

