// Code generated by sql2gogen. DO NOT EDIT.
package actionsgen
	
const getUsers = "select * from users where id = $1 and age > $2;"	
const insertUser = "insert into users( id, name, age, email ) values ( $1, $2, $3, $4 );"

func GetUsers(
	userID string, userAge int,
) (string, []any) {
	return getUsers, []any{
		userID, userAge,
	}
}

func InsertUser(
	userID string, userName string, userAge int, userEmail string,
) (string, []any) {
	return insertUser, []any{
		userID, userName, userAge, userEmail,
	}
}

